[package]
name = "stack-snake"
edition = "2024"
publish = false

[dependencies]
anyhow = "*"
crossbeam-channel = "*"
notify = "*"
pixels = "*"
winit = "*"

[dependencies.stack-assembly]
git = "https://github.com/hannobraun/stack-assembly.git"
